<a href="https://colab.research.google.com/github/VikkasDs/Hotel-Booking-Analysis/blob/main/Sample_EDA_Submission_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project Name**    -

##### **Project Type**    - Hotel Booking Analysis
##### **Contribution**    - Individual
##### **Team Member 1 - VIKASH TIWARI
##### **Team Member 2 -**
##### **Team Member 3 -**
##### **Team Member 4 -**

# **Project Summary -**

Write the summary here within 500-600 words.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

**Write Problem Statement Here.**

#### **Define Your Business Objective?**


Have you ever wondered when the best time of year to book a hotel room is? Or the optimal length of stay in order to get the best daily rate? What if you wanted to predict whether or not a hotel was likely to receive a disproportionately high number of special requests?

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

### Dataset Loading

In [4]:
# Load Dataset
df=pd.read_csv('/Hotel Bookings.csv') #the dataset have been picked directly from local system and not from drive

### Dataset First View

In [5]:
# Dataset First Look
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0.0,1.0,Check-Out,2015-07-03

### Dataset Rows & Columns count

In [8]:
# Dataset Rows & Columns count
df.shape #there are 51390 rows and 32 columns in this dataset

(51390, 32)

### Dataset Information

In [9]:
# Dataset Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51390 entries, 0 to 51389
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           51390 non-null  object
 1   is_canceled                     51390 non-null  int64
 2   lead_time                       51390 non-null  int64
 3   arrival_date_year               51390 non-null  int64
 4   arrival_date_month              51390 non-null  object
 5   arrival_date_week_number        51390 non-null  int64
 6   arrival_date_day_of_month       51390 non-null  int64
 7   stays_in_weekend_nights         51390 non-null  int64
 8   stays_in_week_nights            51390 non-null  int64
 9   adults                          51390 non-null  int64
 10  children                        51386 non-null  float64
 11  babies                          51390 non-null  int64
 12  meal                            51390 non-null  object
 13  country                         50912 non-null  object
 14  market_segment                  51390 non-null  object
 15  distribution_channel            51390 non-null  object
 16  is_repeated_guest               51390 non-null  int64
 17  previous_cancellations          51390 non-null  int64
 18  previous_bookings_not_canceled  51390 non-null  int64
 19  reserved_room_type              51390 non-null  object
 20  assigned_room_type              51390 non-null  object
 21  booking_changes                 51390 non-null  int64
 22  deposit_type                    51390 non-null  object
 23  agent                           42526 non-null  float64
 24  company                         3359 non-null   float64
 25  days_in_waiting_list            51390 non-null  int64
 26  customer_type                   51390 non-null  object
 27  adr                             51390 non-null  float64
 28  required_car_parking_spaces     51389 non-null  float64
 29  total_of_special_requests       51389 non-null  float64
 30  reservation_status              51389 non-null  object
 31  reservation_status_date         51389 non-null  object
dtypes: float64(6), int64(14), object(12)
memory usage: 12.5+ MB

#### Duplicate Values

In [18]:
# Dataset Duplicate Value Count
duplicate_rows= df[df.duplicated(keep=False)]
duplicate_rows

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0.0,1.0,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0.0,1.0,Check-Out,2015-07-03
21,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0.0,1.0,Check-Out,2015-07-07
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0.0,1.0,Check-Out,2015-07-07
39,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,No Deposit,250.0,NaN,0,Transient,137.00,0.0,1.0,Check-Out,2015-07-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51384,City Hotel,1,316,2016,May,21,19,0,2,2,...,Non Refund,1.0,NaN,0,Transient,62.00,0.0,0.0,Canceled,2015-10-22
51385,City Hotel,1,316,2016,May,21,19,0,2,2,...,Non Refund,1.0,NaN,0,Transient,62.00,0.0,0.0,Canceled,2015-10-22
51386,City Hotel,1,316,2016,May,21,19,0,2,2,...,Non Refund,1.0,NaN,0,Transient,62.00,0.0,0.0,Canceled,2015-10-22
51387,City Hotel,1,28,2016,May,21,19,0,2,1,...,No Deposit,NaN,174.0,0,Transient-Party,95.00,0.0,0.0,Canceled,2016-05-04
51388,City Hotel,1,316,2016,May,21,19,0,2,2,...,Non Refund,1.0,NaN,0,Transient,62.00,0.0,0.0,Canceled,2015-10-22

In [19]:
# dropping duplicate rows from the dataset
df=df.drop_duplicates()

In [20]:
#checking number of entries removed as duplicates
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40359 entries, 0 to 51389
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           40359 non-null  object
 1   is_canceled                     40359 non-null  int64
 2   lead_time                       40359 non-null  int64
 3   arrival_date_year               40359 non-null  int64
 4   arrival_date_month              40359 non-null  object
 5   arrival_date_week_number        40359 non-null  int64
 6   arrival_date_day_of_month       40359 non-null  int64
 7   stays_in_weekend_nights         40359 non-null  int64
 8   stays_in_week_nights            40359 non-null  int64
 9   adults                          40359 non-null  int64
 10  children                        40355 non-null  float64
 11  babies                          40359 non-null  int64
 12  meal                            40359 non-null  object
 13  country                         39912 non-null  object
 14  market_segment                  40359 non-null  object
 15  distribution_channel            40359 non-null  object
 16  is_repeated_guest               40359 non-null  int64
 17  previous_cancellations          40359 non-null  int64
 18  previous_bookings_not_canceled  40359 non-null  int64
 19  reserved_room_type              40359 non-null  object
 20  assigned_room_type              40359 non-null  object
 21  booking_changes                 40359 non-null  int64
 22  deposit_type                    40359 non-null  object
 23  agent                           33288 non-null  float64
 24  company                         2643 non-null   float64
 25  days_in_waiting_list            40359 non-null  int64
 26  customer_type                   40359 non-null  object
 27  adr                             40359 non-null  float64
 28  required_car_parking_spaces     40358 non-null  float64
 29  total_of_special_requests       40358 non-null  float64
 30  reservation_status              40358 non-null  object
 31  reservation_status_date         40358 non-null  object
dtypes: float64(6), int64(14), object(12)
memory usage: 10.2+ MB

In [21]:
# Checking for duplicate values and found null after successfully removing duplicates. Now Data Is Duplicate Free
duplicate_rows= df[df.duplicated(keep=False)]
duplicate_rows

Empty DataFrame
Columns: [hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, agent, company, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests, reservation_status, reservation_status_date]
Index: []

[0 rows x 32 columns]

#### Missing Values/Null Values

In [23]:
# Missing Values/Null Values Count
df.isna()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51359,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
51363,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
51368,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
51383,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
51389,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,True,True,True

In [26]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [ ]:
df['price'] = df['price'].replace('?',np.nan)

In [ ]:
# Visualizing the missing values

### What did you know about your dataset?

Answer Here

## ***2. Understanding Your Variables***

In [ ]:
# Dataset Columns

In [ ]:
# Dataset Describe

### Variables Description

Answer Here

### Check Unique Values for each variable.

In [ ]:
# Check Unique Values for each variable.

## 3. ***Data Wrangling***

### Data Wrangling Code

In [ ]:
# Write your code to make your dataset analysis ready.

### What all manipulations have you done and insights you found?

Answer Here.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1

In [ ]:
# Chart - 1 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 2

In [ ]:
# Chart - 2 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 3

In [ ]:
# Chart - 3 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 4

In [ ]:
# Chart - 4 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 5

In [ ]:
# Chart - 5 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 6

In [ ]:
# Chart - 6 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 7

In [ ]:
# Chart - 7 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 8

In [ ]:
# Chart - 8 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 9

In [ ]:
# Chart - 9 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 10

In [ ]:
# Chart - 10 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 11

In [ ]:
# Chart - 11 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 12

In [ ]:
# Chart - 12 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 13

In [ ]:
# Chart - 13 visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 14 - Correlation Heatmap

In [ ]:
# Correlation Heatmap visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

#### Chart - 15 - Pair Plot

In [ ]:
# Pair Plot visualization code

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

Answer Here.

# **Conclusion**

Write the conclusion here.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***